# config.yaml

#tres gros retard
#randomization_factor: 30

#gros retard
# randomization_factor: 13

#faible retard
#randomization_factor: 5

#pas de retard artificiel
randomization_factor: 0

#parteur multiplcateur de CPU %
cpu_factor: 1

#start automatique
auto_start: 1

mysql_control : 1
container_name_or_id : 'witcher-mysql'

WITH_MAIL : True

seuils : {
    "cpu": {"seuil1": 90, "seuil2": 80, "state" : 0, "timestamp": None},
    "memory": {"seuil1": 85, "seuil2": 70, "state" : 0, "timestamp": None},
    "elapse": {"seuil1": 9, "seuil2": 3, "state" : 0, "timestamp": None},
    "mysql": {"state" : 0, "timestamp": None},
    "demon": {"state" : 0, "timestamp": None},
}

